### ISSUE TITLE
Actually test installing this addon once godot asset library mods approve it

### ISSUE THREAD

**Issue by markopolojorgensen** [markopolojorgensen/godot_2d_camera_limiter#1]
https://godotengine.org/asset-library/asset/edit/806

**Comment by akien-mga** [comment]
Well it will work, but you should only have one addon per repo, since the assetlib will download the whole repo at the given commit. So for now it will work fine with your camera limiter addon, but if you add a second addon, it will be installed together with the camera limiter.

**Comment by markopolojorgensen** [comment]
That makes sense, I was assuming there was some functionality to enable picking and choosing which addons from a repo I wanted to enable. I'll rename this repo and have this be just for the camera limiter. 

Thanks for the explanation!
